# version: '3'

# services:
#   web:
#     build: .
#     command: sh -c "uvicorn index:app --reload --port=8000 --host=0.0.0.0"
#     ports:
#       - 8000:8000

version: '3'
services:
  web:
    build: .
    ports:
      - "80:5000"